# Generated by Django 4.2.10 on 2024-04-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
