# Generated by Django 4.2.10 on 2024-04-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
