# Generated by Django 4.2.10 on 2025-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('stories', 'Short Sotires/Novellas'), ('programming', 'Programming Guide'), ('spirituality', 'Spirituality'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
