# Generated by Django 4.2.10 on 2024-03-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='date_posted',
        ),
    ]
