# Generated by Django 4.2.10 on 2024-04-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
