# Generated by Django 4.2.10 on 2024-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_downvotes_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
