# Generated by Django 4.2.10 on 2024-04-07 10:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_remove_post_downvotes_remove_post_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_comments', models.ManyToManyField(related_name='commented_by_users', to='blog.comment')),
                ('user_posts', models.ManyToManyField(related_name='posted_by', to='blog.post')),
            ],
        ),
    ]
