# Generated by Django 4.2.10 on 2024-04-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogadminpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAdminPage',
        ),
    ]
