# Generated by Django 4.2.10 on 2024-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
