# Generated by Django 4.2.10 on 2024-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbs',
        ),
    ]
